# name: cypress
# on:
#   push:
#     branches: [ main ]

# jobs:
#   integration:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: cd EShop && cd client && npm install
#       - run: cd EShop && cd client && npm run cy:headless
