name: CD-auth
on:
  push:
    branches: [ main ]
    paths: 
      - 'EShop/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd EShop && cd auth && docker build -t dcgws21rki/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push dcgws21rki/auth
      - uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud container clusters get-credentials rusnvc-dev
      - run: kubectl rollout restart deployment auth-depl
