
name: deploy-manifest
on:
  push:
    branches: [ main ]
    paths: 
      - 'EShop/infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud container clusters get-credentials rusnvc-dev --zone=europe-west1-b
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
