
name: deploy-manifest
on:
  push:
    branches: [ main ]
    paths: 
      - 'EShop/infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud container clusters get-credentials rusnvc-dev
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
