name: Performance, Integration & CD-client
on:
  push:
    branches: [ main ]
    paths: 
      - 'EShop/client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd EShop && cd client && docker build -t dcgws21rki/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push dcgws21rki/client
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud container clusters get-credentials rusnvc-eshop --zone=europe-west1-b
      - run: kubectl rollout restart deployment client-depl
      
      - run: cd EShop && cd client && npm install
      - run: cd EShop && cd client && npm run cy:headless
      
#       - run: cd EShop && cd client && cd k6
      - uses: grafana/k6-action@v0.2.0
        with:
          filename: EShop\client\k6\client-perf-test.js
#       - run: cd EShop && cd client && cd k6
      - uses: grafana/k6-action@v0.2.0
        with:
          filename: EShop\client\k6\api-perf-test.js
          
#       - run: cd EShop && cd client && cd k6 && k6 run client-perf-test.js
#       - run: cd EShop && cd client && cd k6 && k6 run api-perf-test.js
          
          
#   integration:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: cd EShop && cd client && npm install
#       - run: cd EShop && cd client && npm run cy:headless
#       - uses: cypress-io/github-action@v4
